function getTriangleArea added
rafprzygoda/9.1_functions pull request #1
Opened 2017-05-30 19:20 UTC by rafprzygoda

2017-05-30 21:25 UTC, matwjablonski requested changes

2017-05-30 21:25 UTC, matwjablonski commented on js/scripts.js
> +    if (a <= 0 && h <= 0) {
instead `&&` use `||`

2017-05-30 21:25 UTC, matwjablonski commented on js/scripts.js
> +    } else {
you can just write `return a*h/2` without `else {}`

2017-05-31 17:22 UTC, rafprzygoda commented
Fixed. Add || and delete else.

2017-05-31 22:26 UTC, matwjablonski approved these changes

2017-06-17 20:23 UTC, merged